### ISSUE TITLE
Will some features like backward search be developed?[suggestion]

### ISSUE THREAD

**Issue by LC0117** [aspeddro/tex.nvim#1]
I think it's of great use when writing long article.

**Comment by aspeddro** [comment]
This is already implemented in the language server protocol `texlab`.

Example using `evince`. 

```lua
require('lspconfig').texlab.setup({
  settings = {
      texlab = {
        build = {
          executable = 'latexmk',
          args = { '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f' },
          onSave = true,
          forwardSearchAfter = true,
          isContinuous = false
        },
        forwardSearch = {
          onSave = false,
          executable = 'evince-synctex',
          args = {"-f", "%l", "%p", 'nvim'}
        }
      }
    }
})
```

The command `TexlabForward` go to line.

More details see https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/texlab.lua and https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md

I will soon document the LSP configuration

**Comment by LC0117** [comment]
Thanks for the quick reply. But the documents in [texlab](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md) are about vscode. I'm wondering how to set a config for forward and inverse research for `nvim` and `Skim.app` on macOS.

**Comment by aspeddro** [comment]
You need to change `forwardSearch.executable` and `forwardSearch.args`

[TexLab config Skim](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md#skim)

I don't use macOS, but could you please try it? You just have to put the path to the executable and change the arguments table

```lua
require('lspconfig').texlab.setup({
  settings = {
      texlab = {
        build = {
          executable = 'latexmk',
          args = { '-pdf', '-interaction=nonstopmode', '-synctex=1', '%f' },
          onSave = true,
          forwardSearchAfter = true,
          isContinuous = false
        },
        forwardSearch = {
          onSave = false,
          executable = '/Applications/Skim.app/Contents/SharedSupport/displayline',
          args = {"%l", "%p", "%f"}
        }
      }
    }
})

```

**Comment by LC0117** [comment]
Thanks!
BTW, I searched some docs about skim, and the inverse search can be done by the below config(for some who may encounter the same problem).
1. Install `nvr`
2. Add the config to `init.lua`
```lua
vim.cmd[[
  function! s:write_server_name() abort
    let nvim_server_file = '/tmp/vimtexserver.txt'
    call writefile([v:servername], nvim_server_file)
  endfunction
  autocmd FileType tex call s:write_server_name()
]]
```
3. Open skim.app's preference and choose `sync`
4. Choose `custom` and configure like this
```
cmd: nvr
args: --servername `cat /tmp/vimtexserver.txt` "+%line" "%file"
```
