### ISSUE TITLE
Preview not executable

### ISSUE THREAD

**Issue by MrWelsch** [aspeddro/tex.nvim#3]
Hello, thanks for the great plugin!

Sadly whenever I try to preview my compiled tex file I get:

```
'xdg-open' is not executable
```

I also tried to define the app explicitly (viewer: 'Wondershare PDFelement' and viewer: 'Preview'). Same Error.

**My System:**

M1 Mac Book Air (Monterey)

**Comment by aspeddro** [comment]
`xgd-open` is available in Linux system. macOS use `open` command to launch the default program.

https://apple.stackexchange.com/questions/74353/how-to-launch-pdf-viewer-from-the-terminal

**Comment by aspeddro** [comment]
See https://github.com/aspeddro/tex.nvim/commit/2881a34b23310a825a7ceb9d80ba3651d3b926f4
